name: Create Pack
on:
  push:
    branches-ignore:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create Pack
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH }}
        script: |
          cd "./packs/Faithful-Bedrock-64x"
          git pull
          zip -r "Faithful 64x - 1.19 Experimental.mcpack" . -x "*.git*" -x "*.github*" -x ".gitignore" -x "README.md"
          mv "Faithful 64x - 1.19 Experimental.mcpack" "/var/www/html/database.faithfulpack.net/packs/64x-Bedrock/Experimental"